---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
  namespace: zowe
  labels:
    app.kubernetes.io/name: zowe
    app.kubernetes.io/instance: zowe
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/component: app-server
    app.kubernetes.io/part-of: app-server
    app.kubernetes.io/managed-by: manual
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: zowe
      app.kubernetes.io/instance: zowe
      app.kubernetes.io/component: app-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zowe
        app.kubernetes.io/instance: zowe
        app.kubernetes.io/component: app-server
    spec:
      securityContext:
        runAsUser: 20000
        runAsGroup: 20000
        fsGroup: 20000
      serviceAccountName: zowe-sa
      volumes:
        - name: zowe-runtime
          emptyDir: {}
        - name: zowe-config
          configMap:
            name: zowe-config
        - name: zowe-keystore
          projected:
            sources:
              - secret:
                  name: zowe-certificates-secret
        - name: zowe-workspace
          persistentVolumeClaim:
            claimName: zowe-workspace-pvc
      containers:
        - name: app-server
          image: zowe-docker-release.jfrog.io/ompzowe/app-server:2-ubuntu
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: app-server-port
              containerPort: 7556
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: 7556
            # this should give 18 * periodSeconds(default to 10) seconds about 3 minutes to confirm it's ready
            periodSeconds: 10
            failureThreshold: 18
          livenessProbe:
            tcpSocket:
              port: 7556
            # this should give 3 * periodSeconds(default to 10) seconds about 30 seconds to confirm it's offline
            periodSeconds: 10
            failureThreshold: 3
          command: ["/bin/bash", "-c"]
          args:
            - "/home/zowe/runtime/bin/zwe internal start -c /home/zowe/zowe.yaml"
          env:
            - name: ZWE_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/home/zowe/runtime/bin/zwe internal prestop -c /home/zowe/zowe.yaml"]
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
          volumeMounts:
            - name: zowe-runtime
              mountPath: "/home/zowe/runtime"
            - name: zowe-config
              mountPath: "/home/zowe/zowe.yaml"
              subPath: zowe.yaml
              readOnly: true
            - name: zowe-keystore
              mountPath: "/home/zowe/keystore"
              readOnly: true
            - name: zowe-workspace
              mountPath: "/home/zowe/workspace"
      initContainers:
        - name: init-zowe
          # image: zowe-docker-release.jfrog.io/ompzowe/zowe-launch-scripts:latest
          image: zowe-docker-snapshot.jfrog.io/ompzowe/zowe-launch-scripts:2.0.0-ubuntu.staging
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
          volumeMounts:
            - name: zowe-runtime
              mountPath: "/home/zowe/runtime"
            - name: zowe-workspace
              mountPath: "/home/zowe/workspace"
        - name: update-workspace-permission
          image: busybox:1.28
          command: ['sh', '-c', 'OWNER=`stat -c "%u:%g" /home/zowe/workspace` && PERMISSION=`stat -c "%a" /home/zowe/workspace` && echo "Zowe workspace owner is ${OWNER} with ${PERMISSION} permission" && if [ "${OWNER}" != "20000:20000" -a "${PERMISSION}" != "777" ]; then chown -R 20000:20000 /home/zowe/workspace; fi']
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: zowe-workspace
              mountPath: "/home/zowe/workspace"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
              add:
                - CHOWN
            runAsUser: 0
            runAsGroup: 0
