- name: Update ansible_* (strings) from environment variables if it's not defined
  no_log: True
  set_fact:
    "{{ item }}": "{{ lookup('env',item|upper)|default('') }}"
  when: (item not in vars or item is none or item == '') and lookup('env',item|upper) != ''
  loop:
  - "ansible_ssh_host"
  - "ansible_port"
  - "ansible_user"
  - "ansible_password"

- name: Update zos_zosmf_host from ansible_ssh_host if it's not defined
  no_log: True
  set_fact:
    zos_zosmf_host: "{{ ansible_ssh_host|default('') }}"
  when: zos_zosmf_host == '' or zos_zosmf_host is none

- name: Update zowe_zos_host from ansible_ssh_host if it's not defined
  no_log: True
  set_fact:
    zowe_zos_host: "{{ ansible_ssh_host|default('') }}"
  when: zowe_zos_host == '' or zowe_zos_host is none

- name: Update zowe_external_domain_name from zowe_zos_host if it's not defined
  no_log: True
  set_fact:
    zowe_external_domain_name: "{{ zowe_zos_host|default('') }}"
  when: zowe_external_domain_name == '' or zowe_external_domain_name is none
