---
# ============================================================================
- name: Download Zowe from zowe_build_url if it has value
  when: zowe_build_url is defined
  block:
  - name: Download zowe build if zowe_build_url exists
    get_url:
      url: "{{ zowe_build_url }}"
      dest: "{{ work_dir_local }}/{{ inventory_hostname }}/{{ zowe_build_file }}"
    delegate_to: localhost

  - import_role:
      name: common
      tasks_from: upload_file
    vars:
      filename_to_upload: "{{ zowe_build_file }}"
      file_upload_method: sftp
      file_upload_hashcheck: true

# ============================================================================
# if zowe_build_local is set, upload to z/OS
- name: Download Zowe from zowe_build_local if it has value
  when: zowe_build_local is defined
  block:
  - name: Prepare zowe build locally
    copy:
      src: "{{ zowe_build_local }}"
      dest: "{{ work_dir_local }}/{{ inventory_hostname }}/{{ zowe_build_file }}"
    delegate_to: localhost

  - import_role:
      name: common
      tasks_from: upload_file
    vars:
      filename_to_upload: "{{ zowe_build_file }}"
      file_upload_method: sftp
      file_upload_hashcheck: true
