---
# this playbook runs SZWESAMP(ZWEKRING)

- name: Remove ZWECCAD.jcl if exists
  raw: rm -f "{{ work_dir_remote }}/ZWECCAD.jcl"

- name: Transfer ZWECCAD.jcl to zOS
  block:
    - name: Copy ZWECCAD.jcl to local tmp folder
      copy:
        src: ZWECCAD.jcl
        dest: "{{ work_dir_local }}/{{ inventory_hostname }}/"
      delegate_to: localhost

    - import_role:
        name: common
        tasks_from: upload_file
      vars:
        filename_to_upload: ZWECCAD.jcl
        file_upload_method: scp
        file_upload_hashcheck: false

    - name: Check if ZWECCAD.jcl exists on zOS
      raw: test -f "{{ work_dir_remote }}/ZWECCAD.jcl"
      ignore_errors: True
      register: file_exist
      failed_when: file_exist.rc != 0

- name: Update ZWECCAD.jcl with configurations
  raw: >-
    cat "{{ work_dir_remote }}/ZWECCAD.jcl" | \
    sed -e "s+ZOWEUSER=ZWESVUSR+ZOWEUSER={{ zowe_runtime_user }}+" | \
    sed -e "s+DSNAME=DSNAME+DSNAME={{ zowe_dataset_prefix }}.CERT.USER+" \
    > "{{ work_dir_remote }}/ZWECCAD.jcl"

- name: Check ZWECCAD.jcl changes
  raw: cat "{{ work_dir_remote }}/ZWECCAD.jcl"

- name: Run ZWEKRING.jcl
  import_role:
    name: zos
    tasks_from: run_jcl
  vars:
    jcl_filename: "{{ work_dir_remote }}/ZWECCAD.jcl"
