---
# Configure ZSS to accept JWT

- name: SSO setup
  block:
    - name: Check if setup exists
      raw: tsocmd "RLIST CRYPTOZ *"

    - name: Define profile
      raw: tsocmd "RDEFINE CRYPTOZ {{ zowe_runtime_user }}.SSOJWTKN"

    - name: Add READ access
      raw: tsocmd "PERMIT {{ zowe_runtime_user }}.SSOJWTKN ACCESS(UPDATE) CLASS(CRYPTOZ) ID({{ zowe_runtime_user }})"

    - name: Check if setup exists
      raw: tsocmd "RLIST CRYPTOZ *"

    - name: Activate profile
      raw: |-
        tsocmd "SETROPTS RACLIST(CRYPTOZ)"
        tsocmd "SETROPTS CLASSACT(CRYPTOZ)"

