---
# Configure ZSS to accept JWT

- name: SSO setup
  block:

    - name: Define profile
      raw: |-
        tsocmd "RDEFINE CRYPTOZ SO.SSOJWTKN"
        tsocmd "RDEFINE CRYPTOZ USER.SSOJWTKN"

    - name: Add READ access
      raw: |-
        tsocmd "PERMIT SO.SSOJWTKN ACCESS(UPDATE) CLASS(CRYPTOZ) ID({{ zowe_runtime_user }})"
        tsocmd "PERMIT USER.SSOJWTKN ACCESS(UPDATE) CLASS(CRYPTOZ) ID({{ zowe_runtime_user }})"

    - name: Activate profile
      raw: |-
        tsocmd "SETROPTS RACLIST(CRYPTOZ)"
        tsocmd "SETROPTS CLASSACT(CRYPTOZ)"

