---
# Add client certificate to security system and map it to the user.

- name: Import client certificate to security systems
  block:
    - name: Copy certificate to dataset
      raw: cp "{{ work_dir_remote }}/USER-cert.cer" "//'{{ zowe_dataset_prefix }}.CERT.USER'"

    - name: Import certificate to RACF
      when: zos_security_system == 'RACF'
      raw: |-
        tsocmd "racdcert add('{{ zowe_dataset_prefix }}.CERT.USER') id({{ zowe_runtime_user }}) withlabel('API ML Client') trust"
        tsocmd "SETROPTS RACLIST(DIGTCERT, DIGTRING) REFRESH"
        tsocmd "RACDCERT LIST ID({{ zowe_runtime_user }})"
      ignore_errors: True

    - name: Import certificate to TSS
      when: zos_security_system == 'TSS'
      raw: |-
        tsocmd "TSS ADDTO({{ zowe_runtime_user }}) DIGICERT(ZWECC) LABLCERT('API ML Client certificate') DCDSN('{{ zowe_dataset_prefix }}.CERT.USER') TRUST"
        tsocmd "TSS LIST({{ zowe_runtime_user }}) DIGICERT(ALL)"
      ignore_errors: True

    - name: Import certificate to ACF2
      when: zos_security_system == 'ACF2'
      import_role:
        name: configure
        tasks_from: add_client_certificate_acf2
