---
# Add client certificate to security system and map it to the user.

- name: Import client certificate to security systems
  block:

    - name: Import certificate to RACF
      raw: |-
        tsocmd "racdcert add('{{ zowe_dataset_prefix }}.CERT.USER') id({{ zowe_runtime_user }}) withlabel('API ML Client') trust"
        tsocmd "SETROPTS RACLIST(DIGTCERT, DIGTRING) REFRESH"
        tsocmd "RACDCERT LIST ID({{ zowe_runtime_user }})"
      ignore_errors: True
      when: zos_security_system == 'ACF2'

    - name: Import certificate to TSS
      raw: |-
        tsocmd "TSS ADDTO({{ zowe_runtime_user }}) DIGICERT(ZWECC) LABLCERT('API ML Client certificate') DCDSN('{{ zowe_dataset_prefix }}.CERT.USER') TRUST"
        tsocmd "TSS LIST({{ zowe_runtime_user }}) DIGICERT(ALL)"
      ignore_errors: True
      when: zos_security_system == 'TSS'

    - name: Import certificate to ACF2
      raw: |-
        echo "import certificate"
        cp "{{ work_dir_remote }}/USER-cert.cer" "//'{{ zowe_dataset_prefix }}.CERT.USER'"
        echo "upload finished"
        tsocmd "ACF"
        tsocmd "SET PROFILE({{ zowe_runtime_user }}) DIV(CERTDATA)"
        tsocmd "CHKCERT {{ zowe_runtime_user }}.ZWECC"
        tsocmd "INSERT {{ zowe_runtime_user }}.ZWECC DSNAME('{{ zowe_dataset_prefix }}.CERT.USER') LABEL('API ML Client certificate') TRUST"
      ignore_errors: True
      when: zos_security_system == 'RACF'
