---
# Setup profile and token necessary to enable SSO with JWT

- name: Configure Zowe JWT secret token TSS
  block:
    - name: Create zowe token
      raw: tsocmd "TSS P11TOKEN TOKENADD LABLCTKN({{ zowe_token_name }})"
      ignore_errors: True
    - name: Bind jwtsecret to profile
      raw: tsocmd "TSS P11TOKEN BIND LABLCTKN({{ zowe_token_name }}) TOKNUSER({{ zowe_runtime_user }}) LABLCERT('{{ zowe_token_label }}')"
      ignore_errors: True
    - name: List zowe token certificates
      raw: tsocmd "TSS P11TOKEN TOKENLST LABLCTKN({{ zowe_token_name }})"

