---
# this playbook runs SZWESAMP(ZWEKRING)
- name: Remove ZWEKRING.jcl if exists
  raw: >-
    rm -f "{{ work_dir_remote }}/ZWEKRING.jcl"
    rm -f "{{ work_dir_remote }}/ZWEKRING.raw.jcl"

- name: Copy SZWESAMP(ZWEKRING) to USS
  raw: cp "//'{{ zowe_dataset_prefix }}.SZWESAMP(ZWEKRING)'" "{{ work_dir_remote }}/ZWEKRING.raw.jcl"

- name: Show ip zowe_external_ip_address
  debug:
    var: zowe_external_ip_address

- name: ping hostnmame
  raw: oping -A ipv4 $(hostname)
  when: zowe_external_ip_address is undefined or zowe_external_ip_address is none or zowe_external_ip_address|length == 0

- name: Set ip address
  raw: oping -A ipv4 $(hostname) | sed -n 's/.* (\\(.*\\)).*/\\1/p'
  when: zowe_external_ip_address is undefined or zowe_external_ip_address is none or zowe_external_ip_address|length == 0
  register: zowe_external_ip_address

- name: Show ip zowe_external_ip_address
  debug:
    var: zowe_external_ip_address

- name: Update ZWEKRING.jcl with configurations
  raw: >-
    cat "{{ work_dir_remote }}/ZWEKRING.raw.jcl" | \
    sed -e "s%ALTNAME(IP(127.0.0.1) +%ALTNAME(IP({{ zowe_external_ip_address }}) +%" | \
    sed -e "s%DOMAIN('localhost')) +%DOMAIN('{{ zowe_external_domain_name }})) +%" | \
    sed -e "s%ALTNAME(IP=127.0.0.1 DOMAIN=localhost) +%ALTNAME(IP={{ zowe_external_ip_address }} DOMAIN={{ zowe_external_domain_name }}) +%" \
    > "{{ work_dir_remote }}/ZWEKRING.jcl"

- name: Check ZWEKRING.jcl changes
  raw: >-
    grep -e "^// *SET " \
        -e ALTNAME \
        -e DOMAIN \
        "{{ work_dir_remote }}/ZWEKRING.jcl"

- name: Run ZWEKRING.jcl
  import_role:
    name: zos
    tasks_from: run_jcl
  vars:
    jcl_filename: "{{ work_dir_remote }}/ZWEKRING.jcl"
