---
# this playbook runs SZWESAMP(ZWESSOTK)

- name: Remove ZWESSOTK.jcl if exists
  raw: >-
    rm -f "{{ work_dir_remote }}/ZWESSOTK.jcl"
    rm -f "{{ work_dir_remote }}/ZWESSOTK.raw.jcl"

- name: Copy SZWESAMP(ZWESSOTK) to USS
  raw: cp "//'{{ zowe_dataset_prefix }}.SZWESAMP(ZWESSOTK)'" "{{ work_dir_remote }}/ZWESSOTK.raw.jcl"

- name: Update ZWESSOTK.jcl with configurations
  raw: >-
    cat "{{ work_dir_remote }}/ZWESSOTK.raw.jcl" | \
    sed -e "s%SET  PRODUCT=RACF%SET PRODUCT={{ zos_security_system }}%" | \
    sed -e "s%SET JWTLABEL='jwtsecret'%SET JWTLABEL='{{ zowe_token_label }}'%" | \
    sed -e "s%SET SSOTOKEN=%SET SSOTOKEN='{{ zowe_token_name }}'%" \
    > "{{ work_dir_remote }}/ZWESSOTK.jcl"

- name: Check ZWESSOTK.jcl changes
  raw: >-
    grep -e "^// *SET " \
        -e PRODUCT \
        -e JWTDSNAM \
        -e JWTLABEL \
        -e SSOTOKEN \
        "{{ work_dir_remote }}/ZWESSOTK.jcl"

- name: Run ZWESSOTK.jcl
  import_role:
    name: zos
    tasks_from: run_jcl
  vars:
    jcl_filename: "{{ work_dir_remote }}/ZWESSOTK.jcl"
