---
# This task finds the zowe-start.sh in known folders

# Variables:
# - zowe_instance_dir
# - zowe_root_dir
# Output:
# - zowe_start_path

# validate variables
- import_role:
    name: common
    tasks_from: validate_variables
  vars:
    variable_list:
    - zowe_root_dir
    - zowe_instance_dir

- name: Locate zowe-start.sh
  block:
  - name: Init zowe_start_path variable
    set_fact:
      zowe_start_path: ""
  - name: Check if zowe-start.sh is located at instanceDir
    raw: test -f {{ zowe_instance_dir }}/bin/zowe-start.sh && echo "{{ zowe_instance_dir }}/bin/zowe-start.sh" | tr -d '\n'
    register: zowe_start_at_instancedir
    ignore_errors: yes
    when: zowe_start_path == ""
  - name: Set zowe_start_path to {{ zowe_start_at_instancedir.stdout }}
    set_fact:
      zowe_start_path: "{{ zowe_start_at_instancedir.stdout }}"
    when: zowe_start_path == "" and zowe_start_at_instancedir.stdout != ''
  - name: Check if zowe-start.sh is located at rootDir
    raw: test -f {{ zowe_root_dir }}/scripts/zowe-start.sh && echo "{{ zowe_root_dir }}/scripts/zowe-start.sh" | tr -d '\n'
    register: zowe_start_at_rootdir
    ignore_errors: yes
    when: zowe_start_path == ""
  - name: Set zowe_start_path to {{ zowe_start_at_rootdir.stdout }}
    set_fact:
      zowe_start_path: "{{ zowe_start_at_rootdir.stdout }}"
    when: zowe_start_path == "" and zowe_start_at_rootdir.stdout != ''
  - name: Show zowe_start_path value
    debug:
      var: zowe_start_path
  - name: Check if zowe_start_path has a value
    fail:
      msg: Cannot find zowe-start.sh
    when: zowe_start_path == ""
