---
# This task finds the zwe command in known folders

# Variables:
# - zowe_root_dir
# Output:
# - zowe_zwe_command

# validate variables
- import_role:
    name: common
    tasks_from: validate_variables
  vars:
    variable_list:
    - zowe_root_dir

- name: Locate zwe command
  block:
  - name: Init zowe_zwe_command variable
    set_fact:
      zowe_zwe_command: ""
  - name: Check if zwe is located at rootDir
    raw: test -f {{ zowe_root_dir }}/bin/zwe && echo "{{ zowe_root_dir }}/bin/zwe" | tr -d '\n'
    register: zowe_zwe_at_rootdir
    ignore_errors: yes
    when: zowe_zwe_command == ""
  - name: Set zowe_zwe_command to {{ zowe_zwe_at_rootdir.stdout }}
    set_fact:
      zowe_zwe_command: "{{ zowe_zwe_at_rootdir.stdout }}"
    when: zowe_zwe_command == "" and zowe_zwe_at_rootdir.stdout != ''
  - name: Show zowe_zwe_command value
    debug:
      var: zowe_zwe_command
