---
# Show all Zowe Job Logs

# ============================================================================
- name: Show final zowe.yaml
  raw: cat "{{ zowe_instance_dir }}/zowe.yaml"

# ============================================================================
- import_role:
    name: configure
    tasks_from: locate_xmem

# ============================================================================
# Show zowe job log
- import_role:
    name: zos
    tasks_from: show_job_log
  vars:
    show_job_log_id:
    show_job_log_owner: '*'
    show_job_log_name: "{{ zowe_job_prefix }}{{ zowe_instance_id }}SV"

- import_role:
    name: zos
    tasks_from: show_job_log
  when: zowe_xmem_stc_name != ""
  vars:
    show_job_log_id:
    show_job_log_owner: '*'
    show_job_log_name: "{{ zowe_xmem_stc_name }}"

# ============================================================================
# Show ZWESECUR log
- include_role:
    name: zos
    tasks_from: list_jobs
  vars:
    list_jobs_name: "ZWESECUR"
- include_role:
    name: zos
    tasks_from: show_job_log
  vars:
    show_job_log_id: '{{ item.split(",")[0] }}'
    show_job_log_owner: '*'
    show_job_log_name: "*"
  loop: "{{ list_jobs_result.stdout_lines }}"

# ============================================================================
# Show ZWEKRING log
- include_role:
    name: zos
    tasks_from: list_jobs
  vars:
    list_jobs_name: "ZWEKRING"
- include_role:
    name: zos
    tasks_from: show_job_log
  vars:
    show_job_log_id: '{{ item.split(",")[0] }}'
    show_job_log_owner: '*'
    show_job_log_name: "*"
  loop: "{{ list_jobs_result.stdout_lines }}"

# ============================================================================
# Show ZWENOKYR log
- include_role:
    name: zos
    tasks_from: list_jobs
  vars:
    list_jobs_name: "ZWENOKYR"
- include_role:
    name: zos
    tasks_from: show_job_log
  vars:
    show_job_log_id: '{{ item.split(",")[0] }}'
    show_job_log_owner: '*'
    show_job_log_name: "*"
  loop: "{{ list_jobs_result.stdout_lines }}"

# ============================================================================
- name: List install log dir
  raw: ls -l "{{ zowe_install_logs_dir }}"
  ignore_errors: True

- name: Show Zowe installation logs
  raw: find "{{ zowe_install_logs_dir }}" -type f | xargs -i sh -c 'echo ">>>>>>>>>>>>>>>>>>>>>>>> {} >>>>>>>>>>>>>>>>>>>>>>>" && cat {}'
  ignore_errors: True

# ============================================================================
- name: List runtime log dir
  raw: ls -l "{{ zowe_instance_dir }}/logs"
  ignore_errors: True

- name: Show Zowe runtime logs
  raw: find "{{ zowe_instance_dir }}/logs" -type f | xargs -i sh -c 'echo ">>>>>>>>>>>>>>>>>>>>>>>> {} >>>>>>>>>>>>>>>>>>>>>>>" && cat {}'
  ignore_errors: True
