---
# Transfer files to remote directory

- import_role:
    name: common
    tasks_from: validate_variables
  vars:
    variable_list:
      - work_dir_remote
      - work_dir_local
      - inventory_hostname
      - filename

- name: Check if work_dir_remote has a value
  fail:
    msg: work_dir_remote is required
  when: work_dir_remote is not defined or work_dir_remote is none or work_dir_remote == ''

- name: Transfer {{ filename }} to zOS
  block:
    - name: Copy {{ filename }} to local tmp folder
      copy:
        src: "{{ filename }}"
        dest: "{{ work_dir_local }}/{{ inventory_hostname }}/"
      delegate_to: localhost

    - import_role:
        name: common
        tasks_from: upload_file
      vars:
        filename_to_upload: "{{ filename }}"
        file_upload_method: scp
        file_upload_hashcheck: false

    - name: Check if {{ filename }} exists on zOS
      raw: test -f "{{ work_dir_remote }}/{{ filename }}"
      ignore_errors: True
      register: file_exist
      failed_when: file_exist.rc != 0

