---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: zowe
  labels:
    app: zowe
    tier: gateway
spec:
  # FIXME: customize this value to match your environment
  type: LoadBalancer
  selector:
    app: zowe
    tier: gateway
  ports:
    - protocol: TCP
      port: 7554
      targetPort: 7554
      appProtocol: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  namespace: zowe
  labels:
    app: zowe
    tier: gateway
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gateway-service
              port:
                number: 7554
    # FIXME: customize this value to match your environment
    # host: localhost
