################################################################################
# This program and the accompanying materials are made available under the terms of the
# Eclipse Public License v2.0 which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-v20.html
#
# SPDX-License-Identifier: EPL-2.0
#
# Copyright Contributors to the Zowe Project.
################################################################################

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zowe-workspace-claim
  namespace: zowe
spec:
  # FIXME: StorageClass should be predefined
  #        hostpath is a StorageClass created by Docker Desktop
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
