---
# This playbook runs sanity test on an existing Zowe instance

# ============================================================================
# validate variables
- import_role:
    name: common
    tasks_from: validate_variables
  vars:
    variable_list:
    - zowe_sanity_test_root_dir
    - zowe_root_dir
    - zowe_instance_dir
    - zos_zosmf_port
    - zowe_proclib_membername
    - zowe_job_prefix
    - zowe_zlux_port
    - zowe_apiml_gateway_port
    - zowe_jobs_api_port
    - zowe_mvs_api_port
    - zowe_sanity_test_testcases

# ============================================================================
- name: Delete old reports
  file:
    path: "{{ work_dir_local }}/{{ inventory_hostname }}/reports"
    state: absent
  delegate_to: localhost

# ============================================================================
- name: Prepare sanity test folder
  command: npm install --no-audit
  args:
    chdir: "{{ zowe_sanity_test_root_dir }}"
  delegate_to: localhost

# ============================================================================
- name: test Zowe instance
  command: npm test -- {{ zowe_sanity_test_testcases | default('') }}
  args:
    chdir: "{{ zowe_sanity_test_root_dir }}"
  environment:
    ZOWE_ROOT_DIR: "{{ zowe_root_dir }}"
    ZOWE_INSTANCE_DIR: "{{ zowe_instance_dir }}"
    SSH_HOST: "{{ ansible_ssh_host }}"
    SSH_PORT: "{{ ansible_port }}"
    SSH_USER: "{{ ansible_user }}"
    SSH_PASSWD: "{{ ansible_password }}"
    ZOSMF_PORT: "{{ zos_zosmf_port }}"
    ZOWE_DS_MEMBER: "{{ zowe_proclib_membername }}"
    ZOWE_JOB_PREFIX: "{{ zowe_job_prefix }}"
    ZOWE_ZLUX_HTTPS_PORT: "{{ zowe_zlux_port }}"
    ZOWE_API_MEDIATION_GATEWAY_HTTP_PORT: "{{ zowe_apiml_gateway_port }}"
    ZOWE_EXPLORER_JOBS_PORT: "{{ zowe_jobs_api_port }}"
    ZOWE_EXPLORER_DATASETS_PORT: "{{ zowe_mvs_api_port }}"
    DEBUG: "{{ zowe_sanity_test_debug_mode | default('') }}"
  delegate_to: localhost
