---
# ==============================================================================
# Constants
# ==============================================================================

# this should list all known cross memory server stc we ever setup during install
zowe_known_xmem_proc_stcs:
- ZWESIS01
- ZWEXMSTC
- ZWESISTC

# ==============================================================================
# Variables should be verified and overwrittern.
# ==============================================================================
# default zowe runtime root directory
zowe_root_dir: ~/zowe
# instanceDir
zowe_instance_dir: ~/.zowe/instance

# cross memory server proclib
zowe_xmem_proclib:
