---
- name: Reset zowe_launch_components for docker install
  set_fact:
    zowe_launch_components: zss

- import_role:
    name: configure

- name: Attach new line to instance.env to make sure we don't accidentally append to last line
  raw: echo ""  >> "{{ zowe_instance_dir }}/instance.env"

# zowe_launch_components reset may not work, let's make sure ZWE_LAUNCH_COMPONENTS
# is defined in instance.env
- name: Check if ZWE_LAUNCH_COMPONENTS exists in instance.env
  raw: grep ZWE_LAUNCH_COMPONENTS '{{ zowe_instance_dir }}/instance.env'
  ignore_errors: True
  register: check_zwe_launch_components_existence

# FIXME: the reason why we don't ensure ZWE_LAUNCH_COMPONENTS exists in instance.env
#        in configure role is verifying backward compatibility?
- name: Attach ZWE_LAUNCH_COMPONENTS if instance.env doesn't have this entry
  when: check_zwe_launch_components_existence.rc != 0
  raw: echo "ZWE_LAUNCH_COMPONENTS={{ zowe_launch_components }}" >> '{{ zowe_instance_dir }}/instance.env'

- name: Make zss available externally
  raw: echo "ZWED_agent_https_ipAddresses=0.0.0.0"  >> "{{ zowe_instance_dir }}/instance.env"

- name: Show instance.env
  raw: cat "{{ zowe_instance_dir }}/instance.env"