---
- name: get docker logs
  set_fact:
    container_logs: ""

- name: get docker logs of container {{container_id}}
  raw: docker logs {{container_id}}
  register: container_logs
  when: container_id is defined
  delegate_to: localhost
  ignore_errors: True

- name: get docker logs using docker ps
  # raw: docker logs $(docker ps -a -q --filter ancestor={{zowe_docker_image}}:{{zowe_docker_tag}})
  raw: docker logs $(docker ps -a -q 2>&1 | head -n 1)
  register: container_logs
  when: container_id is not defined
  delegate_to: localhost
  ignore_errors: True

- debug:
      var: container_logs