---
# ============================================================================
# download from Artifactory if zowe_docker_image_url exists
- name: Download Zowe docker image from zowe_docker_image_url if it has value
  when: zowe_docker_image_url is defined and zowe_docker_image_url != ''
  block:
  - name: Download zowe build if zowe_docker_image_url exists
    get_url:
      url: "{{ zowe_docker_image_url }}"
      dest: "{{ work_dir_local }}/{{ inventory_hostname }}/zowe_docker_image.tar"
    delegate_to: localhost

  - name: Update zowe_docker_image_local
    set_fact:
      zowe_docker_image_local: "{{ work_dir_local }}/{{ inventory_hostname }}/zowe_docker_image.tar"


# ============================================================================
# load Docker image if zowe_docker_image_local exists
- name: Download Zowe from zowe_docker_image_local if it has value
  when: zowe_docker_image_local is defined and zowe_docker_image_local != ''
  block:
  - name: Load docker image
    raw: docker load --input "{{ zowe_docker_image_local }}"
    register: docker_load_result
    delegate_to: localhost
  # we made assumption the tar file only contains one docker image
  - set_fact: 
      docker_image_loaded: "{{ docker_load_result.stdout | regex_findall('Loaded image:[ ]+(.+)') | join('') | regex_findall('(.+):(.+)') }}"
  - set_fact: 
      zowe_docker_image: "{{ docker_image_loaded[0][0] }}"
      zowe_docker_tag: "{{ docker_image_loaded[0][1] }}"
  - debug:
      msg: "Docker imaged loaded is: {{ zowe_docker_image }}:{{ zowe_docker_tag }}"

# ============================================================================
# pull image from Docker Hub
- name: Pull docker image {{zowe_docker_image}}:{{zowe_docker_tag}} from Docker Hub
  when: zowe_docker_image_local is undefined or zowe_docker_image_local == ''
  raw: docker pull {{zowe_docker_image}}:{{zowe_docker_tag}}
  delegate_to: localhost
