---
# ============================================================================
- name: Update zowe_test_user from ansible_user if it's not defined
  # hide log to avoid exposing zowe_test_user
  no_log: True
  set_fact:
    zowe_test_user: "{{ hostvars[inventory_hostname].ansible_user }}"
  when: zowe_test_user == '' or zowe_test_user is none

- name: Update zowe_test_password from ansible_password if it's not defined
  # hide log to avoid exposing zowe_test_password
  no_log: True
  set_fact:
    zowe_test_password: "{{ hostvars[inventory_hostname].ansible_password }}"
  when: zowe_test_password == '' or zowe_test_password is none

# ============================================================================
# verify variables
- import_role:
    name: common
    tasks_from: validate_variables
  vars:
    variable_list:
    - zowe_zos_host
    - zowe_external_domain_name
    - zowe_zss_port
    - zowe_zlux_port
    - zowe_jobs_api_port
    - zowe_apiml_gateway_port

- name: Wait for being able to login to ZSS
  uri:
    # ZSS is always running on z/OS side
    url: "{{ zowe_zss_https | ternary('https', 'http') }}://{{ zowe_zos_host }}:{{ zowe_zss_port }}/login"
    follow_redirects: none
    method: POST
    body_format: json
    body: 
      username: "{{ zowe_test_user }}"
      password: "{{ zowe_test_password }}"
    validate_certs: false
    status_code:
    - 200
  register: _result
  until: _result.status == 200
  retries: "{{ wait_for_zowe_service_retries | int }}"
  delay: "{{ wait_for_zowe_service_delay | int }}"
  when: '"zss" in zowe_launch_components'
  delegate_to: localhost
  # hide log to avoid exposing zowe_test_user and zowe_test_password
  no_log: True

- name: Wait for APIML port {{zowe_apiml_gateway_port}} to be available
  uri:
    url: "https://{{ zowe_external_domain_name }}:{{zowe_apiml_gateway_port}}"
    follow_redirects: none
    method: GET
    validate_certs: false
  register: _result
  until: _result.status == 200
  retries: "{{ wait_for_zowe_service_retries | int }}"
  delay: "{{ wait_for_zowe_service_delay | int }}"
  delegate_to: localhost

- name: Wait for being able to login to App Server
  uri:
    url: "https://{{ zowe_external_domain_name }}:{{zowe_zlux_port}}/auth"
    follow_redirects: none
    method: POST
    body_format: json
    body: 
      username: "{{ zowe_test_user }}"
      password: "{{ zowe_test_password }}"
    validate_certs: false
    status_code:
    - 200
    - 204
  register: _result
  until: _result.status == 200
  retries: "{{ wait_for_zowe_service_retries | int }}"
  delay: "{{ wait_for_zowe_service_delay | int }}"
  delegate_to: localhost
  # hide log to avoid exposing zowe_test_user and zowe_test_password
  no_log: True

- name: Wait for being able to login to API Catalog
  uri:
    url: "https://{{ zowe_external_domain_name }}:{{zowe_apiml_gateway_port}}/api/v1/apicatalog/auth/login"
    follow_redirects: none
    method: POST
    body_format: json
    body: 
      username: "{{ zowe_test_user }}"
      password: "{{ zowe_test_password }}"
    validate_certs: false
    status_code:
    - 200
    - 204
  register: _result
  until: _result.status == 204
  retries: "{{ wait_for_zowe_service_retries | int }}"
  delay: "{{ wait_for_zowe_service_delay | int }}"
  delegate_to: localhost
  # hide log to avoid exposing zowe_test_user and zowe_test_password
  no_log: True
