---
# Verifies a component's status
# input:
# component_id: required
# is_service: required (true or false)

- set_fact:
    prepare_environment: ". {{ zowe_root_dir }}/bin/internal/prepare-environment.sh -c {{ zowe_instance_dir }} -r {{ zowe_root_dir }}"

# Discovery Port: 7553, may want to change to a generic variable
- name: Check component's service status
  when: is_service is true
  block:
  - name: Retrieve service information
    raw: >-
      {{ prepare_environment }} && node {{ zowe_root_dir }}/bin/utils/curl.js {{ ansible_ssh_host }} 7553 /eureka/apps/{{ component_id }} >> {{ work_dir_remote }}/verify-ext-serviceid.xml && \
      {{ prepare_environment }} && read_xml {{ work_dir_remote }}/verify-ext-serviceid.xml .application.instance.status && \
      {{ prepare_environment }} && read_xml {{ work_dir_remote }}/verify-ext-serviceid.xml .application.instance.app && \
      rm -rf {{ work_dir_remote }}/verify-ext-serviceid.xml
    # Think about maybe moving the rm command to be the first command to run
    register: service_status

  - name: Check status of the {{ service_status.stdout_lines[1] }}
    debug:
      msg: "{{ service_status.stdout_lines[1] }} - STATUS: {{ service_status.stdout_lines[0] }}"
    when: service_status.stdout_lines[0] == 'UP'
    
  - fail:
      msg: "{{ service_status.stdout_lines[1] }} - STATUS: {{ service_status.stdout_lines[0] }}"
    when: service_status.stdout_lines[0] != 'UP'

- name: Check component's plugin is installed
  when: is_service is false
  block:
  - name: Retrieve list of all plugins currently installed
  # https://tvt4188.svl.ibm.com:8544/plugins
    raw: >-
      {{ prepare_environment }} && node {{ zowe_root_dir }}/bin/utils/curl.js {{ ansible_ssh_host }} 8544 /plugins >> {{ work_dir_remote }}/verify-ext-plugin.json }} && \
      {{ prepare_environment }} && read_json {{ work_dir_remote }}/verify-ext-plugin.json .pluginDefinitions[].identifier && \
      rm -rf {{ work_dir_remote }}/verify-ext-plugin.json
    register: plugins_list
  
  - name: Check if component's plugin is listed
    debug:
      msg: OK! - Plugin Exists
    when: component_id in plugins_list.stdout_lines

  - fail:
      msg: FAILED! - Plugin does not exist
    when: component_id not in plugins_list.stdout_lines
