---
# Verify extensions are installed and running
# Input: component_id - required

# ============================================================================
# validate variables
- import_role:
    name: common
    tasks_from: validate_variables
  vars:
    variable_list:
    - zowe_root_dir
    - zowe_extension_dir
    - zowe_instance_dir
    - work_dir_remote

# ============================================================================
- name: Verify {{ component_id }} component instance is running
  when: component_id is defined
  block:
    # Call script that will verify the current component's instance
    - name: Verify Component Instance
      import_role:
        name: zos
        tasks_from: run_script
      vars:
        script_chdir: "{{ zowe_root_dir }}/bin"
        script_filename: ./zowe-verify-component.sh
        script_parameters: "-i \"{{ zowe_instance_dir }}\" -r \"{{ zowe_root_dir }}\" -c \"{{ component_id }}\""