---
# Verifies all extensions and components are installed and running

# IDEA: Maybe perform this task through a shell script function

- set_fact:
    prepare_environment: ". {{ zowe_root_dir }}/bin/internal/prepare-environment.sh -c {{ zowe_instance_dir }} -r {{ zowe_root_dir }}"

# ============================================================================
- name: Get list of all components
  raw: "{{ prepare_environment }} && list_all_components"
  register: all_components

- name: Verify Components
  include_tasks: verify.yml
  vars:
    component_id: "{{ curr_component }}"
  with_items: "{{ all_components.stdout_lines }}"
  loop_control:
    loop_var: curr_component