---
# ============================================================================
- import_role:
    name: configure
    tasks_from: locate_xmem

- import_role:
    name: configure
    tasks_from: locate_zowe_stop

# ============================================================================
- name: Stop Cross Memory Server
  import_role:
    name: zos
    tasks_from: opercmd
  vars:
    opercmd: "P {{ zowe_xmem_stc_name }}"

- name: Stop Zowe
  raw: "{{ zowe_stop_path }}"
