---
# ==============================================================================
# Constants
# ==============================================================================

# this should list all known cross memory server stc we ever setup during install
zowe_known_xmem_proc_stcs:
- ZWESIS01
- ZWEXMSTC
- ZWESISTC

# 360 * 10 seconds = 1hour
wait_for_zowe_service_retries: 360
# Every 10 seconds
wait_for_zowe_service_delay: 10

# ==============================================================================
# Variables should be verified and overwrittern.
# ==============================================================================
# default zowe runtime root directory
zowe_root_dir: ~/zowe
# instanceDir
zowe_instance_dir: ~/.zowe/instance

# optional, default to ansible_ssh_host
# required for zD&T (external IP is different from internal IP)
zowe_external_domain_name:
# optional, default to ansible_user
zowe_test_user:
# optional, default to ansible_password
zowe_test_password:

# cross memory server proclib
zowe_xmem_proclib:
# ports will be tested
zowe_zlux_port: 8544
zowe_jobs_api_port: 8545
zowe_apiml_gateway_port: 7554
