---
# ==============================================================================
# Constants
# ==============================================================================
# 360 * 10 seconds = 1hour
wait_for_zowe_service_retries: 30
# Every 10 seconds
wait_for_zowe_service_delay: 10
# If we clean up history job output befor starting new
cleanup_zowe_job_history: True

# ==============================================================================
# Variables should be verified and overwrittern.
# ==============================================================================
# optional, default to ansible_ssh_host
# required for zD&T (external IP is different from internal IP)
zowe_external_domain_name:
# optional, default to ansible_user
zowe_test_user:
# optional, default to ansible_password
zowe_test_password:

# ports will be tested
zowe_zlux_port: 8544
zowe_jobs_api_port: 8545
zowe_apiml_gateway_port: 7554
