---

# ============================================================================
# Clean up history job output
- import_role:
    name: configure
    tasks_from: purge_job_outputs
  when: cleanup_zowe_job_history

# ============================================================================
- import_role:
    name: configure
    tasks_from: locate_xmem

- import_role:
    name: configure
    tasks_from: locate_zowe_start

# ============================================================================
- name: Start Cross Memory Server
  import_role:
    name: zos
    tasks_from: opercmd
  vars:
    opercmd: "S {{ zowe_xmem_stc_name }}"

- name: Start Zowe
  raw: "{{ zowe_start_path }}"

# ============================================================================
# Wait for services started
- import_role:
    name: start
    tasks_from: wait_for_zowe
