---

# ============================================================================
- import_role:
    name: configure
    tasks_from: locate_xmem
- name: Check if zowe_xmem_stc_name has a value
  fail:
    msg: Cannot find cross memory server
  when: zowe_xmem_stc_name == ""

# ============================================================================
- name: Start Cross Memory Server
  include_role:
    name: zos
    tasks_from: opercmd
  vars:
    opercmd: "S {{ zowe_xmem_stc_name }},REUSASID=YES"

- name: Start Zowe
  include_role:
    name: zos
    tasks_from: run_zwe
  vars:
    parameters: "start"

# ============================================================================
# Wait for services started
- import_role:
    name: start
    tasks_from: wait_for_zowe
