---

# ============================================================================
# Clean up history job output
- import_role:
    name: configure
    tasks_from: purge_job_outputs
  when: cleanup_zowe_job_history

# ============================================================================
- import_role:
    name: configure
    tasks_from: locate_xmem
- name: Check if zowe_xmem_stc_name has a value
  fail:
    msg: Cannot find cross memory server
  when: zowe_xmem_stc_name == ""

- import_role:
    name: configure
    tasks_from: zowe_zwe_command
- name: Check if zowe_zwe_command has a value
  fail:
    msg: Cannot find zowe-start.sh
  when: zowe_zwe_command == ""

# ============================================================================
- name: Start Cross Memory Server
  import_role:
    name: zos
    tasks_from: opercmd
  vars:
    opercmd: "S {{ zowe_xmem_stc_name }},REUSASID=YES"

- name: Start Zowe
  raw: "{{ zowe_zwe_command }} start"

# ============================================================================
# Wait for services started
- import_role:
    name: start
    tasks_from: wait_for_zowe
