---
# this is the most common tasks
- include_role:
    name: zos
    tasks_from: upload_scripts_if_not_exists
  vars:
    usine_file: "{{ item }}"
  loop:
  - opercmd.rexx
  - show_job_log.rexx
  - list_jobs.rexx
