# This playbook will run zwe command on the server

# input:
# - function_name: required
# - function_parameters: optional

- name: Check if zowe_root_dir has a value
  fail:
    msg: zowe_root_dir is required
  when: zowe_root_dir is not defined or zowe_root_dir is none or zowe_root_dir == ''

- name: Update zowe.yaml configuration
  raw: >-
    touch {{ zos_uss_user_profile }} && \
    . {{ zos_uss_user_profile }} \
    {{ zowe_environment_variable_overrides | default('') }} && \
    test -f "{{ zowe_root_dir }}/bin/libs/index.sh" && \
    export ZWE_zowe_runtimeDirectory="{{ zowe_root_dir }}" && \
    . "{{ zowe_root_dir }}/bin/libs/index.sh" && \
    cd "{{ zowe_root_dir }}" && \
    {{ function_name }} {{ function_parameters | default('') }}
