# ============================================================================
- fail:
    msg: work_dir_remote is required
  when: work_dir_remote is not defined or work_dir_remote is none or work_dir_remote == ''

- name: Check if opercmd exists on zOS
  raw: test -f "{{ work_dir_remote }}/opercmd"
  ignore_errors: True
  register: zowe_install_opercmd_exists

- name: Transfer opercmd to zOS
  when: zowe_install_opercmd_exists is failed
  block:
  - name: Copy opercmd to local tmp folder
    copy:
      src: opercmd
      dest: "{{ work_dir_local }}/{{ inventory_hostname }}/"
    delegate_to: localhost

  - import_role:
      name: common
      tasks_from: upload_file
    vars:
      filename_to_upload: opercmd
      zos_upload_method: scp

  - name: Add executive permission to opercmd
    raw: chmod g+x "{{ work_dir_remote }}/opercmd"
