---
# install zowe convenience build
# the build should have been uploaded to "{{ work_dir_remote }}/{{ zowe_build_file }}"
# ============================================================================
- import_role:
    name: common
    tasks_from: validate_variables
  vars:
    variable_list:
    - work_dir_remote
    - zowe_root_dir
    - zowe_dataset_prefix

- name: Check if Zowe build has been uploaded
  raw: test -f '{{ work_dir_remote }}/{{ zowe_build_file }}'

- name: Extract Zowe
  raw: >-
    rm -fr "{{ zowe_root_dir }}" && \
    mkdir -p "{{ zowe_root_dir }}" && \
    cd "{{ zowe_root_dir }}" && \
    pax -ppx -rf '{{ work_dir_remote }}/{{ zowe_build_file }}'

- name: Initialize zowe.yaml
  raw: >-
    rm -fr "{{ zowe_instance_dir }}" && \
    mkdir -p "{{ zowe_instance_dir }}" && \
    cd "{{ zowe_instance_dir }}" && \
    pax -ppx -rf '{{ work_dir_remote }}/{{ zowe_build_file }}'

- name: Install Zowe
  import_role:
    name: zos
    tasks_from: run_script
  vars:
    script_chdir: "{{ zowe_root_dir }}/bin"
    script_filename: ./zwe
    script_parameters: "install -i \"{{ zowe_root_dir }}\" -h \"{{ zowe_dataset_prefix }}\" -l \"{{ zowe_install_logs_dir }}\""

- name: List log dir
  raw: ls -l "{{ zowe_install_logs_dir }}"
  ignore_errors: True

- name: Show installation log
  raw: find {{ zowe_install_logs_dir }} -name "zowe-install-*.log" -type f | xargs -i sh -c 'echo ">>>>>>>>>>>>>>>>>>>>>>>> {} >>>>>>>>>>>>>>>>>>>>>>>" && cat {}'
  ignore_errors: True
