# Compared to zos run_script task, this task can be used to source {{ zowe_root_dir }}/bin/internal/prepare-environment.sh
# This task can only be used when zowe is fully installed
# Mainly used to generally run a script
# work_dir_remote folder

# input:
# - script_chdir: optional
# - script_filename: required
# - script_parameters: optional

- name: Check if work_dir_remote has a value
  fail:
    msg: work_dir_remote is required
  when: work_dir_remote is not defined or work_dir_remote is none or work_dir_remote == ''

- name: Run {{ script_filename }} from {{ script_chdir | default(work_dir_remote) }}
  raw: >-
    touch {{ zos_uss_user_profile }} && \
    . {{ zos_uss_user_profile }} \
    {{ zowe_environment_variable_overrides | default('') }} && \
    cd "{{ script_chdir | default(work_dir_remote) }}" && \
    {{ script_filename }} {{ script_parameters | default('') }}
