---

# Delete racf Keyrings and certificates we've created
# ============================================================================
- name: Unbind jwtsecret from zowe token
  raw: tsocmd "RACDCERT UNBIND(TOKEN(ZWETOKEN) SEQNUM(00000050)) FORCE"
  ignore_errors: True
# Unbind from token before removing
- name: Unbind jwtsecret from zowe token
  raw: tsocmd "RACDCERT UNBIND(TOKEN({{ zowe_token_name }}) ID({{ zowe_runtime_user }}) LABEL('{{ zowe_token_label }}')) FORCE"
  ignore_errors: True

- name: List zowe token certificates
  raw: tsocmd "RACDCERT LISTTOKEN({{ zowe_token_name }})"
  ignore_errors: True

- name: Remove Zowe RACF personal certficates from keyrings
  raw: tsocmd "RACDCERT ID({{ zowe_runtime_user }}) REMOVE(LABEL('{{ item[0] }}') RING({{ item[1] }}))"
  loop: "{{ zowe_known_keyring_personal_certificates |product(zowe_known_keyring_names)|list }}"
  ignore_errors: True

- name: Remove Zowe RACF certauth certficates from keyrings
  raw: tsocmd "RACDCERT ID({{ zowe_runtime_user }}) REMOVE(CERTAUTH LABEL('{{ item[0] }}') RING({{ item[1] }}))"
  loop: "{{ zowe_known_keyring_certauth_certificates |product(zowe_known_keyring_names)|list }}"
  ignore_errors: True

- name: Deleting Zowe RACF keyrings
  raw: tsocmd "RACDCERT ID({{ zowe_runtime_user }}) DELRING({{ item }})"
  loop: "{{ zowe_known_keyring_names }}"
  ignore_errors: True

- name: Remove Zowe RACF personal certficates
  raw: tsocmd "RACDCERT ID({{ zowe_runtime_user }}) DELETE(LABEL('{{ item }}')"
  loop: "{{ zowe_known_keyring_personal_certificates }}"
  ignore_errors: True 

- name: Remove Zowe RACF certauth certficates
  raw: tsocmd "RACDCERT CERTAUTH DELETE(LABEL('{{ item }}')"
  loop: "{{ zowe_known_keyring_certauth_certificates }}"
  ignore_errors: True 

- name: List user's RACF certificates
  raw: tsocmd "RACDCERT ID({{ zowe_runtime_user }})"
  ignore_errors: True 
