---
# Delete Keyrings and certificates we've created

#TODO - zip 1610 - update to support acf2 and tss

# ============================================================================
# check variables
- import_role:
    name: common
    tasks_from: validate_variables
  vars:
    variable_list:
    - work_dir_remote
    - zowe_known_runtime_users
    - zowe_known_started_tasks
    - zowe_known_facility_profiles
    - zowe_known_xmem_stc_users

# ============================================================================

- import_role:
    name: zowe
    tasks_from: uninstall_security_config_racf
  when: zos_security_system == 'RACF'

- import_role:
    name: zowe
    tasks_from: uninstall_security_config_acf2
  when: zos_security_system == 'ACF2'

- import_role:
    name: zowe
    tasks_from: uninstall_security_config_tss
  when: zos_security_system == 'TSS'