---
# Delete racf security config we've created reverting ZWESECUR.jcl
# ============================================================================

- name: Deleting started tasks
  raw: tsocmd 'RDELETE STARTED ({{ item }}.*)'
  loop: "{{ zowe_known_started_tasks }}"
  ignore_errors: True

- name: Deleting facility profiles
  raw: tsocmd 'RDELETE FACILITY ({{ item }})'
  loop: "{{ zowe_known_facility_profiles }}"
  ignore_errors: True

- name: Refresh STARTED
  raw: tsocmd 'SETR RACLIST(STARTED) REFRESH'
  ignore_errors: True

- name: Refresh FACILITY
  raw: tsocmd 'SETR RACLIST(FACILITY) REF'
  ignore_errors: True
