---
# ==============================================================================
# Constants
# ==============================================================================
# 360 * 10 seconds = 1hour
wait_for_zowe_service_retries: 60
# Every 10 seconds
wait_for_zowe_service_delay: 5
# zowe docker image
zowe_docker_image: ompzowe/server-bundle
zowe_docker_tag: amd64

# ==============================================================================
# Variables should be verified and overwrittern.
# ==============================================================================
# default z/OSMF port. Optional, default value is ansible_ssh_host
zos_zosmf_host:
# default z/OSMF port
zos_zosmf_port: 10443
zowe_zss_https: True
zowe_zss_port: 8542
zowe_launch_components: zss

zowe_zlux_terminal_telnet_port: 23
# The security type of the tn3270 connection - valid values are blank('') for telnet, or 'tls'
zowe_zlux_terminal_telnet_security_type:

zowe_root_dir: ~/
