---
# input:
# - zowe_build_url: optional, full url of zowe build
# - zowe_build_local: optional, path to zowe build exists locally
- name: Install Zowe Convenience Build
  hosts: all
  gather_facts: false
  become: false

  tasks:

  # ============================================================================
  # prepare ansible environment for install
  - import_role:
      name: common

  - import_role:
      name: zos

  # ============================================================================
  # uninstall zowe
  - name: Uninstall Zowe
    when: zowe_uninstall_before_install|default(True)
    block:
    - import_role:
        name: zowe
        tasks_from: uninstall
    - import_role:
        name: fmid
        tasks_from: uninstall

  # Upload zowe
  - import_role:
      name: common
      tasks_from: upload-zowe

  # # ============================================================================
  # # Install Zowe
  # - import_role:
  #     name: zowe

  # # ============================================================================
  # # Configure Zowe
  # - import_role:
  #     name: configure

  # # ============================================================================
  # # Start Zowe
  # - import_role:
  #     name: start
  #   when: not skip_start|default(False)
