---
  # input:
  # - zowe_build_url: optional, full url of zowe build
  # - zowe_build_local: optional, path to zowe build exists locally
  - name: Test Docker
    hosts: all
    gather_facts: false
    become: false
  
    tasks:
  
    # ============================================================================
    # prepare ansible environment for install
    - import_role:
        name: common
  
    - import_role:
        name: zos

    # ============================================================================
    # uninstall zowe
    - name: Uninstall Zowe
      when: zowe_uninstall_before_install|default(True)
      block:
      - import_role:
          name: zowe
          tasks_from: uninstall
      - import_role:
          name: fmid
          tasks_from: uninstall
  
    # ============================================================================
    # Upload zowe
    - import_role:
        name: common
        tasks_from: upload-zowe
  
    # ============================================================================
    # Install Zowe
    - import_role:
        name: zowe

    # ============================================================================
    # Configure Zowe
    - name: Reset zowe_launch_components for docker install
      set_fact:
        zowe_launch_components: zss

    - import_role:
        name: configure

    - name: Attach new line to instance.env to make sure we don't accidentally append to last line
      raw: echo ""  >> "{{ zowe_instance_dir }}/instance.env"

    # zowe_launch_components reset may not work, let's make sure ZWE_LAUNCH_COMPONENTS
    # is defined in instance.env
    - name: Check if ZWE_LAUNCH_COMPONENTS exists in instance.env
      raw: grep ZWE_LAUNCH_COMPONENTS '{{ zowe_instance_dir }}/instance.env'
      ignore_errors: True
      register: check_zwe_launch_components_existence

    # FIXME: the reason why we don't ensure ZWE_LAUNCH_COMPONENTS exists in instance.env
    #        in configure role is verifying backward compatibility?
    - name: Attach ZWE_LAUNCH_COMPONENTS if instance.env doesn't have this entry
      when: check_zwe_launch_components_existence.rc != 0
      raw: echo "ZWE_LAUNCH_COMPONENTS={{ zowe_launch_components }}" >> '{{ zowe_instance_dir }}/instance.env'

    - name: Make zss available externally
      raw: echo "ZWED_agent_http_ipAddresses=0.0.0.0"  >> "{{ zowe_instance_dir }}/instance.env"

    - name: Show instance.env
      raw: cat "{{ zowe_instance_dir }}/instance.env"

    # ============================================================================
    # Start Zowe
    - import_role:
        name: start
      when: not skip_start|default(False)
    
    - import_role:
        name: docker
