---
# input:
# - zowe_ext_url: optional, full url of zowe extenion
# - zowe_ext_local: optional, path to zowe extension that exists locally
- name: Zowe Install Extensions
  hosts: all
  gather_facts: false
  become: false

  tasks:

  # ============================================================================
  # prepare ansible environment for install
  - import_role:
      name: common
  - import_role:
      name: zos

  # ============================================================================
  # Check if instance is SMPE install, if so, we need to update zowe_root_dir
  - import_role:
      name: zos
      tasks_from: detect_zowe_instance

  # ============================================================================
  # Run zowe extension installation
  - import_role:
      name: ext
