---
- name: Test Docker
  hosts: all
  gather_facts: false
  become: false

  tasks:
  # Configure Zowe
  - name: Reset zowe_launch_components for docker install
    set_fact:
      zowe_launch_components: app-server

  - import-playbook: install.yml

  - import_role:
      name: docker