---
- name: Show Zowe Job Logs
  hosts: all
  gather_facts: false
  become: false

  tasks:

  # ============================================================================
  # prepare ansible environment for install
  - import_role:
      name: common
  - import_role:
      name: zos

  # ============================================================================
  # Show all Zowe Job runtime logs
  - import_role:
      name: configure
      tasks_from: show_logs

  # ============================================================================
  # Show Zowe Docker Logs
  - import_role:
      name: docker
      when: zowe_docker_image_url is defined and zowe_docker_image_url != ''
      tasks_from: docker-logs
