---
- name: Sanity test on Zowe instance
  hosts: all
  gather_facts: false
  become: false

  tasks:

  # ============================================================================
  # prepare ansible environment for install
  - import_role:
      name: common
  - import_role:
      name: zos

  # ============================================================================
  # Check if instance is SMPE install, if so, we need to update zowe_root_dir
  - import_role:
      name: zos
      tasks_from: detect_zowe_instance

  # ============================================================================
  # Run sanity test
  - import_role:
      name: verify

  - name: Check fingerprint is correct
    raw: >-
        touch {{ zos_uss_user_profile }} && \
        . {{ zos_uss_user_profile }} \
        {{ zowe_environment_variable_overrides | default('') }} && \
        cd "{{ zowe_root_dir }}" && \
        bin/zowe-verify-authenticity.sh -l "{{ zowe_install_logs_dir }}"
    ignore_errors: False

