apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cleanup-static-definitions
  namespace: zowe
  labels:
    app: zowe
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 20000
            runAsGroup: 20000
            fsGroup: 20000
          volumes:
            - name: zowe-runtime
              emptyDir: {}
            - name: zowe-instance
              emptyDir: {}
            - name: zowe-config
              configMap:
                name: zowe-config
            - name: zowe-workspace
              persistentVolumeClaim:
                claimName: zowe-workspace-claim
          restartPolicy: OnFailure
          containers:
            - name: cleanup-static-definitions
              # image: zowe-docker-release.jfrog.io/ompzowe/zowe-launch-scripts:latest
              image: zowe-docker-snapshot.jfrog.io/ompzowe/zowe-launch-scripts:1.24.0-ubuntu-amd64.users-jack-k8s-yaml
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - /component/bin/internal/init-container.sh; /home/zowe/instance/bin/utils/cleanup-static-definitions.sh
              volumeMounts:
                - name: zowe-runtime
                  mountPath: "/home/zowe/runtime"
                - name: zowe-instance
                  mountPath: "/home/zowe/instance"
                - name: zowe-config
                  mountPath: "/home/zowe/instance/instance.env"
                  subPath: instance.env
                  readOnly: true
                - name: zowe-workspace
                  mountPath: "/home/zowe/instance/workspace"
