---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-api
  labels:
    app: zowe
spec:
  selector:
    matchLabels:
      app: zowe
      tier: jobs-api
  replicas: 1
  template:
    metadata:
      labels:
        app: zowe
        tier: jobs-api
    spec:
      securityContext:
        runAsUser: 20000
        runAsGroup: 20000
        fsGroup: 20000
      volumes:
        - name: zowe-runtime
          emptyDir: {}
        - name: zowe-instance
          emptyDir: {}
        - name: zowe-config
          configMap:
            name: zowe-config
        - name: zowe-certificates-cm
          configMap:
            name: zowe-certificates-cm
        - name: zowe-certificates-secret
          secret:
            secretName: zowe-certificates-secret
        - name: zowe-workspace
          persistentVolumeClaim:
            claimName: zowe-workspace-claim
      containers:
        - name: jobs-api
          image: zowe-docker-release.jfrog.io/ompzowe/jobs-api:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "400m"
          ports:
            - containerPort: 8080
          command: ["/home/zowe/instance/bin/internal/run-zowe.sh"]
          volumeMounts:
            - name: zowe-runtime
              mountPath: "/home/zowe/runtime"
            - name: zowe-instance
              mountPath: "/home/zowe/instance"
            - name: zowe-config
              mountPath: "/home/zowe/instance/instance.env"
              subPath: instance.env
              readOnly: true
            - name: zowe-certificates-cm
              mountPath: "/home/zowe/keystore/zowe-certificates.env"
              subPath: zowe-certificates.env
              readOnly: true
            - name: zowe-certificates-secret
              mountPath: "/home/zowe/keystore/keystore.p12"
              subPath: keystore.p12
              readOnly: true
            - name: zowe-certificates-secret
              mountPath: "/home/zowe/keystore/truststore.p12"
              subPath: truststore.p12
              readOnly: true
            - name: zowe-certificates-secret
              mountPath: "/home/zowe/keystore/keystore.key"
              subPath: keystore.key
              readOnly: true
            - name: zowe-certificates-secret
              mountPath: "/home/zowe/keystore/keystore.cert"
              subPath: keystore.cert
              readOnly: true
            - name: zowe-certificates-secret
              mountPath: "/home/zowe/keystore/localca.cert"
              subPath: localca.cert
              readOnly: true
            - name: zowe-workspace
              mountPath: "/home/zowe/instance/workspace"
      initContainers:
        - name: init-zowe
          image: zowe-docker-snapshot.jfrog.io/ompzowe/zowe-launch-scripts:0.0.1-ubuntu.users-jack-k8s-yaml-32
          volumeMounts:
            - name: zowe-runtime
              mountPath: "/home/zowe/runtime"
            - name: zowe-instance
              mountPath: "/home/zowe/instance"
