name: Build Zowe Base Images
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: 'Set to true if we want to release the base images'
        required: false
        default: ''

jobs:
  build-ubuntu-amd64:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: zowe-docker-snapshot.jfrog.io
    steps:
      - uses: actions/checkout@v2

      - name: Update registry for release
        if: ${{ github.event.inputs.release == 'true' }}
        run: |
          echo "DOCKER_REGISTRY=zowe-docker-release.jfrog.io" >> $GITHUB_ENV

      - name: Login to Zowe registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: build amd64 image
        working-directory: containers/base/ubuntu/amd64
        run: |
          docker build --no-cache=true -t ${{ env.DOCKER_REGISTRY }}/ompzowe/base:latest-ubuntu-amd64 .
          docker push ${{ env.DOCKER_REGISTRY }}/ompzowe/base:latest-ubuntu-amd64

      - name: define manifest
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker manifest create ${{ env.DOCKER_REGISTRY }}/ompzowe/base:latest-ubuntu --amend ompzowe/base:latest-ubuntu-amd64
          docker manifest push ${{ env.DOCKER_REGISTRY }}/ompzowe/base:latest-ubuntu

  build-ubi-amd64:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: zowe-docker-snapshot.jfrog.io
    steps:
      - uses: actions/checkout@v2

      - name: Update registry for release
        if: ${{ github.event.inputs.release == 'true' }}
        run: |
          echo "DOCKER_REGISTRY=zowe-docker-release.jfrog.io" >> $GITHUB_ENV

      - name: Login to Zowe registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Login to registry.redhat.io
        uses: docker/login-action@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_DEVELOPER_USER }}
          password: ${{ secrets.REDHAT_DEVELOPER_PASSWORD }}

      - name: build ubi image
        working-directory: containers/base/ubi/amd64
        run: |
          docker build --no-cache=true -t ${{ env.DOCKER_REGISTRY }}/ompzowe/base:latest-ubi-amd64 .
          docker push ${{ env.DOCKER_REGISTRY }}/ompzowe/base:latest-ubi-amd64

      - name: define manifest
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker manifest create ${{ env.DOCKER_REGISTRY }}/ompzowe/base:latest-ubi --amend ompzowe/base:latest-ubi-amd64
          docker manifest push ${{ env.DOCKER_REGISTRY }}/ompzowe/base:latest-ubi
