name: Dummy workflow to enable manual triggering
on:
  workflow_dispatch:
    inputs:
      test:
        description: 'dummy input'
        required: false
        default: ''
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
