# A sample workflow which checks out the code, builds a container
# image using Docker and scans that image for vulnerabilities using
# Snyk. The results are then uploaded to GitHub Security Code Scanning
#
# For more examples, including how to limit scans to only high-severity
# issues, monitor images for newly disclosed vulnerabilities in Snyk and
# fail PR checks for new vulnerabilities, see https://github.com/snyk/actions/

name: Snyk Container

on: 
  workflow_dispatch:
    types:
      - mytrigger
    inputs:
      imageName:
        description: 'Please enter full path of image'     
        required: true

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Setup image list matrix
        id: setup-image-matrix
        run: |
          IMAGES_LIST=$(cat manifest.json.template | jq -r '.imageDependencies[] | "{\"image\": \"" + .registry + "/" + .name + ":" + .tag + "\"},"')
          echo ::set-output name=image-matrix::{\"include\":[$IMAGES_LIST]}
    outputs:
      image-matrix: ${{ steps.setup-image-matrix.outputs.image-matrix }}

  snyk:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.image-matrix) }}
    steps:
    - uses: actions/checkout@v2

    - name: Run Snyk to check Docker image for vulnerabilities
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true
      uses: snyk/actions/docker@master
      # we don't have original Dockerfile, cannot generate and upload sarif 
      with:
        image: ${{ matrix.image }}
        command: test
