name: Build ompzowe/zowe-launch-scripts
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: 'Set to "true" if we want to release the images'
        required: false
        default: ''
env:
  IMAGE_BASE_DIR: containers/zowe-launch-scripts

jobs:
  build-ubuntu-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: zowe-actions/shared-actions/envvars-global@main

      - uses: zowe-actions/shared-actions/docker-prepare@main
        with:
          registry-user: ${{ secrets.ARTIFACTORY_USERNAME }}
          registry-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          release: ${{ github.event.inputs.release }}
          base-directory: ${{ env.IMAGE_BASE_DIR }}
          linux-distro: ubuntu
          cpu-arch: amd64

      - uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_TOKEN }}

      - name: prepare build context
        run: |
          ./${IMAGE_BASE_DIR}/prepare-workdir.sh
          cp -r ./${IMAGE_BASE_DIR}/tmp ./${IMAGE_BASE_DIR}/ubuntu/amd64/zowe
        with:
          GITHUB_PR_ID: ${{ github.event.pull_request.number }}

      - uses: zowe-actions/shared-actions/docker-build-local@main
        timeout-minutes: 5

  build-ubuntu-s390x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: zowe-actions/shared-actions/envvars-global@main

      - uses: zowe-actions/shared-actions/docker-prepare@main
        with:
          registry-user: ${{ secrets.ARTIFACTORY_USERNAME }}
          registry-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          release: ${{ github.event.inputs.release }}
          base-directory: ${{ env.IMAGE_BASE_DIR }}
          linux-distro: ubuntu
          cpu-arch: s390x

      - uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_TOKEN }}

      - name: prepare build context
        run: |
          ./${IMAGE_BASE_DIR}/prepare-workdir.sh
          cp -r ./${IMAGE_BASE_DIR}/tmp ./${IMAGE_BASE_DIR}/ubuntu/s390x/zowe
        with:
          GITHUB_PR_ID: ${{ github.event.pull_request.number }}

      - uses: zowe-actions/shared-actions/docker-build-zlinux@main
        with:
          zlinux-host: ${{ secrets.ZLINUX_HOST }}
          zlinux-ssh-user: ${{ secrets.ZLINUX_SSH_USER }}
          zlinux-ssh-key: ${{ secrets.ZLINUX_SSH_KEY }}
          zlinux-ssh-passphrase: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}
        timeout-minutes: 10

  define-ubuntu-manifest:
    needs:
      - build-ubuntu-amd64
      - build-ubuntu-s390x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: zowe-actions/shared-actions/envvars-global@main

      - uses: zowe-actions/shared-actions/docker-prepare@main
        with:
          registry-user: ${{ secrets.ARTIFACTORY_USERNAME }}
          registry-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          release: ${{ github.event.inputs.release }}
          base-directory: ${{ env.IMAGE_BASE_DIR }}
          linux-distro: ubuntu

      - uses: zowe-actions/shared-actions/docker-manifest@main
        with:
          linux-distro: ubuntu
          cpu-arch-list: "amd64 s390x"
          extra-manifests: "latest {major} {major}.{minor} {major}.{minor}.{patch} latest-ubuntu {major}-ubuntu {major}.{minor}-ubuntu"
        timeout-minutes: 2

  build-ubi-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: zowe-actions/shared-actions/envvars-global@main

      - uses: zowe-actions/shared-actions/docker-prepare@main
        with:
          registry-user: ${{ secrets.ARTIFACTORY_USERNAME }}
          registry-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          release: ${{ github.event.inputs.release }}
          base-directory: ${{ env.IMAGE_BASE_DIR }}
          linux-distro: ubi
          cpu-arch: amd64
          redhat-registry: ${{ env.DEFAULT_REDHAT_DOCKER_REGISTRY }}
          redhat-registry-user: ${{ secrets.REDHAT_DEVELOPER_USER }}
          redhat-registry-password: ${{ secrets.REDHAT_DEVELOPER_PASSWORD }}

      - uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_TOKEN }}

      - name: prepare build context
        run: |
          ./${IMAGE_BASE_DIR}/prepare-workdir.sh
          cp -r ./${IMAGE_BASE_DIR}/tmp ./${IMAGE_BASE_DIR}/ubi/amd64/zowe
        with:
          GITHUB_PR_ID: ${{ github.event.pull_request.number }}

      - uses: zowe-actions/shared-actions/docker-build-local@main
        timeout-minutes: 5

  build-ubi-s390x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: zowe-actions/shared-actions/envvars-global@main

      - uses: zowe-actions/shared-actions/docker-prepare@main
        with:
          registry-user: ${{ secrets.ARTIFACTORY_USERNAME }}
          registry-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          release: ${{ github.event.inputs.release }}
          base-directory: ${{ env.IMAGE_BASE_DIR }}
          linux-distro: ubi
          cpu-arch: s390x

      - uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_TOKEN }}

      - name: prepare build context
        run: |
          ./${IMAGE_BASE_DIR}/prepare-workdir.sh
          cp -r ./${IMAGE_BASE_DIR}/tmp ./${IMAGE_BASE_DIR}/ubi/s390x/zowe
        with:
          GITHUB_PR_ID: ${{ github.event.pull_request.number }}

      - uses: zowe-actions/shared-actions/docker-build-zlinux@main
        with:
          zlinux-host: ${{ secrets.ZLINUX_HOST }}
          zlinux-ssh-user: ${{ secrets.ZLINUX_SSH_USER }}
          zlinux-ssh-key: ${{ secrets.ZLINUX_SSH_KEY }}
          zlinux-ssh-passphrase: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}
          redhat-registry: ${{ env.DEFAULT_REDHAT_DOCKER_REGISTRY }}
          redhat-registry-user: ${{ secrets.REDHAT_DEVELOPER_USER }}
          redhat-registry-password: ${{ secrets.REDHAT_DEVELOPER_PASSWORD }}
        timeout-minutes: 10

  define-ubi-manifest:
    needs:
      - build-ubi-amd64
      - build-ubi-s390x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: zowe-actions/shared-actions/envvars-global@main

      - uses: zowe-actions/shared-actions/docker-prepare@main
        with:
          registry-user: ${{ secrets.ARTIFACTORY_USERNAME }}
          registry-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          release: ${{ github.event.inputs.release }}
          base-directory: ${{ env.IMAGE_BASE_DIR }}
          linux-distro: ubi

      - uses: zowe-actions/shared-actions/docker-manifest@main
        with:
          linux-distro: ubi
          cpu-arch-list: "amd64 s390x"
          extra-manifests: "latest-ubi {major}-ubi {major}.{minor}-ubi"
        timeout-minutes: 2
