name: Update zwe documentation

on:
  # Will eventually run this automatically when v2 is out
  # push:
  #   branches:
  #     - v2.x/staging
  workflow_dispatch:

env:
  DOCS_SITE_ZWE_COMMAND_REFERENCE_DIR: docs/appendix/zwe_server_command_reference
  # Will change this to a docs staging branch (or master branch) when v2 is out
  DOCS_SITE_BRANCH: users/carson/test_zwe_doc_automation # TODO change to v2-docs-branch
  ZWE_DOC_GENERATION_DIR: .dependency/zwe_doc_generation

jobs:
  update-zwe-documentation:
    name: Update zwe documentation on docs-site
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate zwe documentation
        run: node ${{ env.ZWE_DOC_GENERATION_DIR }}
      
      - name: Open PR to docs-site
        run: |
          echo ">>>>>Cloning docs site"
          git clone https://zowe-robot:${{ secrets.ZOWE_ROBOT_TOKEN }}@github.com/zowe/docs-site.git
          git config --global user.email "zowe-robot@users.noreply.github.com"
          git config --global user.name "Zowe Robot"
          cd docs-site
          git checkout ${{ env.DOCS_SITE_BRANCH }}
          echo ">>>>>Copying generated zwe command documentation to docs site"
          cp ../${{ env.ZWE_DOC_GENERATION_DIR }}/generated/* ${{ env.DOCS_SITE_ZWE_COMMAND_REFERENCE_DIR }}
          echo ">>>>>Committing and pushing changes to documentation"
          git add ${{ env.DOCS_SITE_ZWE_COMMAND_REFERENCE_DIR }}
          if git commit -s -m"Update zwe command reference"; then git push && echo ">>>>>Pushed changes to ${{ env.DOCS_SITE_BRANCH }}"; else echo ">>>>>No update to documentation, not pushing commit"; fi
