name: Update zwe documentation

on:
  # Will eventually run this automatically when v2 is out
  # push:
  #   branches:
  #     - v2.x/staging
  workflow_dispatch:

jobs:
  update-zwe-documentation:
    name: Update zwe documentation on docs-site
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate zwe documentation
        run: node .dependency/zwe_doc_generation
      
      - name: Open PR to docs-site
        run: |
          git clone https://zowe-robot:${{ secrets.ZOWE_ROBOT_TOKEN }}@github.com/zowe/docs-site.git
          git config --global user.email "zowe-robot@users.noreply.github.com"
          git config --global user.name "Zowe Robot"
          cd docs-site
          git checkout users/carson/test_zwe_doc_automation
          cp ../.dependency/zwe_doc_generation/generated/* docs/appendix/zwe_server_command_reference
          ls -la docs/appendix/zwe_server_command_reference
